spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8088"
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

security:
  jwt:
    ttl: PT15M
    secret: ${JWT_SECRET}
    issuer: auth-service
  refresh:
    ttl: P7D
