server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: morning.com.services.auth

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://auth-db:3306/authdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

security:
  jwt:
    secret: mxeuGN155Wg98ds+dYeamwUilCt+TGBYsYgfxjLOtF4=    # supply via env var / Kubernetes secret
    ttl: PT1H                # ISO-8601 duration (1 hour)
    issuer: auth-service
  login:
    max-failed-attempts: 5
    lock-duration: PT5M      # ISO-8601 duration
