server:
  port: 0
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

springdoc:
  packagesToScan: morning.com.services.auth
  cache:
    disabled: true
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/authdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,sbom

security:
  jwt:
    private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDeVNE/VMbZKdH0dotN9MkEOseFQOycG3JYv2dOAwA67/UicDjohvLTkY7LBfS43jHnB0lzqkqudGiHfvcJeKk73ldEFboaNa58LWA4LVpFBk6tYmFzx8xtk3N802R3Ynerln1AVIbOP6VjdGybjr30fKtfr7W8Xi7kx/2d6Yi7Lx3KZ3JDCFbUkOy2g12SwhHeFle2AVcTIx5b3BgOtU8ALSuibOA2MrmA8QvRUgWHnQH9b49syCL0gJclEepNOG1DL5QSh9PrrNNpBzYr9OE6TWf5r0U5XhRaH170zStBfCO9IdZGOenRjmpXomWWo8p8gw2tK8kpuX6L1cuf2B4TAgMBAAECggEAEVXfsuZzUr92BW+w0PVDLzc+E1/Kkyl4sv7JmUWWoQHQxUymw0qyaFizH5VpTXjVv0PMMF6Y0B13gQkfTffAilB90Ws4RY7l+fy3wemXXkZtoAtJufNcNzcGDDeXX8+nsRNc1MVCdZZ02NpdFYv9t7B41E8pBnT5hxEo70UkSiPvHfDMQPl/xHri/9U14LtCyLZYM1zX5tKPxFEd4XvvlG7aAAKhD58ujSr4OiJdKIe4Ow9amj1Z6wyWu79bJOvp5pbLkub96sn2vJrJOfbMP2qBOgiXfuGxkIRyMiiQT0jN3wPbSeEGukHStImxfxtK4JjMpcEufDKSjPjqtte3YQKBgQD3j6akba4ZCjRS8NdCkhbniN6//jGQ1661uwXjFlBiMtUCj89Ua4Lox+V4yL3b9U6GAiUhwfeWYEaeaOWIajYY9WoeN0JNakLK5aGgTqDYAynm2N7h4+YT1SdleErjhe2nSeSMjX4R4kx73tht8RzycALnUMil9ppEyibOiXr9KQKBgQDl6P9qpqx3ANXdEU89EnJHSnCO6luvNDepHDvLom9+EUFk8lIlLcSluKsdv86cps1+jDHMEmtX9MoqA7VnyM4WDpz5IMdwLED6Dn4Kp7jsJd4JXgrtB3T5S3SutchkzAh3cw16uwXB7W0q+NGuQ2VHeNQNLxt8TgWJvEy2XHqs2wKBgQDkw8E5NwVnrC9X6ajxonA5+xfkETCaaUTQOIgjJg6X/+MpH912ZHcvRvF9YPtZVGEAouDPRh/VvRfk8IgTPBrLi5VJYMULJsOcHQDzU1V858eDxCqKUX/eGd3y/WsuvycyrKzfWS0Dt7v3x6D2T5XxTqLQQK1599zs7mVX/GFDqQKBgGUBT/US9IHzpAFTMXSrPfmEAp9G5rC6SBnLhZmY61J/UjN/Igeja9lCoCqZsbOwtGb8QIRfMzmZGZgLuQ63cZLPKLdqZzQovQMeitEzjlJw8HM9FZ+8vu8m70QyKK/f03hm220n7Qedv3A5kCT3Bu+3bbG9GF4sCNLSHwGe72YxAoGBAKiJkVe6DnPV0Jm9s9STeqRsGH5WpwCb2z2sTFk/gWFdT4/i9/x3GfTAtXmyKlrJMe4Gagl4VhDYI+JNiKXEmdOhYKfLJ+1ffiA58QqLWHuDMU9JhzCvnKmD7BUuerX7ytOZgiHLo9QF6FSnMLDdR37gOz1M2mPFzNVn7V589gQq
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3lTRP1TG2SnR9HaLTfTJBDrHhUDsnBtyWL9nTgMAOu/1InA46Iby05GOywX0uN4x5wdJc6pKrnRoh373CXipO95XRBW6GjWufC1gOC1aRQZOrWJhc8fMbZNzfNNkd2J3q5Z9QFSGzj+lY3Rsm4699HyrX6+1vF4u5Mf9nemIuy8dymdyQwhW1JDstoNdksIR3hZXtgFXEyMeW9wYDrVPAC0romzgNjK5gPEL0VIFh50B/W+PbMgi9ICXJRHqTThtQy+UEofT66zTaQc2K/ThOk1n+a9FOV4UWh9e9M0rQXwjvSHWRjnp0Y5qV6JllqPKfIMNrSvJKbl+i9XLn9geEwIDAQAB
    key-id: auth-key
    ttl: PT1H                # ISO-8601 duration (1 hour)
    issuer: auth-service
  refresh:
    ttl: P7D
  login:
    max-failed-attempts: 5
    lock-duration: PT5M      # ISO-8601 duration
