server:
  port: 8060
  forward-headers-strategy: framework

app:
  cors:
    origins: https://app.example.com,https://admin.example.com

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
      discovery:
        locator:
          enabled: true
      routes:
      - id: auth-service
        uri: lb://auth-service
        predicates:
          - Path=/auth/**
        filters:
          - RewritePath=/auth/v3/api-docs(?<path>.*), /v3/api-docs$\{path}
      - id: jwk
        uri: lb://auth-service
        predicates:
          - Path=/.well-known/openid-configuration
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  cache:
    disabled: true
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
  api-docs:
    version: openapi_3_1

management:
  tracing:
    sampling:
      probability: 1.0
